version: 2.1
jobs:
  test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          command: mvn test
      - run:
          command: bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN} -r r-romettino/ceri-m1-techniques-de-test -f target/site/jacoco/jacoco.xml
      - run:
          command: "curl -L -X PATCH -H 'Accept: application/vnd.github+json' -H \"Authorization: Bearer ${GIST_TOKEN}\" -H 'X-GitHub-Api-Version: 2022-11-28' https://api.github.com/gists/f9ec335757ad99f50fb47eaefd8fd91c -d \"{\\\"files\\\":{\\\"badge.svg\\\":{\\\"content\\\":\\\"$(cat ./target/site/badges/checkstyle-result.svg | sed 's/\"/\\\\\\\"/g')\\\"}}}\""
      - add_ssh_keys:
          fingerprints:
            - "SHA256:8Yluob+EQvKL1dmkfM1DJyPhovPDBCKvqTiWS3mRq74"
      - run:
          command: gh-pages --dist target/reports/apidocs/
workflows:
  build-and-test:
    jobs:
      - test:
        filters:
          branches:
            only: main